# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c379db814ca8911cae32ba8defba2e9dfaefbbd810ac2f055aad559fb059c343093a07b76b48cdf4f44d0b24a7d687dd2dc0a99fe7964511c503aca118104f96

test:
  secret_key_base: 99fbbee615b75e820194cd9cc46ae5d927e93bb6c0f9f583f20eb598a0934951da4901dbf1afe1c072e4f54ccdb5293daf0884478316fa8e0260d8774b9fd74d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
